#!/bin/sh
stack ghc -- \
  --make xmonad.hs \
  -i \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 \
  -o "$1"

exec stack ghc -- \
  --make xmonadctl.hs \
  -i \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 
